apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: beacon-chain
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: beacon-chain
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: beacon-chain
  updatePolicy:
    updateMode: Auto
