apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: validator-tls
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: validator
spec:
  secretName: validator-tls
  dnsNames:
  - validator
  issuerRef:
    name: cert-manager
