apiVersion: v1
kind: Service
metadata:
  name: eth2stats
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: eth2stats
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: eth2stats