apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: eth2stats
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: eth2stats
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: eth2stats
  updatePolicy:
    updateMode: Auto
