apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: encrypted-secrets
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: encrypted-secrets
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: encrypted-secrets
  updatePolicy:
    updateMode: Auto
