apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: external-dns
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: external-dns
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-dns
  resourcePolicy:
    containerPolicies:
    - containerName: external-dns
      minAllowed:
        cpu: 10m
        memory: 10Mi
  updatePolicy:
    updateMode: Auto
