apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: slasher-tls
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: slasher
spec:
  secretName: slasher-tls
  dnsNames:
  - slasher
  issuerRef:
    name: cert-manager
