apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: slasher
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: slasher
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: slasher
  updatePolicy:
    updateMode: Auto
